# Generated by Django 6.1 on 2026-08-17 13:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Space',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('Workspace', 'Workspace'), ('Meeting room', 'Meeting room'), ('Conference', 'Conference')], max_length=50)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=12)),
                ('price_unit', models.CharField(choices=[('hour', 'hour'), ('day', 'day')], max_length=10)),
                ('min_duration', models.IntegerField(default=1, help_text='Minimum booking duration in units (hours or days)')),
                ('max_duration', models.IntegerField(default=24, help_text='Maximum booking duration in units (hours or days)')),
                ('capacity', models.IntegerField(help_text='Maximum capacity of the space')),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('duration', models.DecimalField(decimal_places=2, help_text='Duration in hours or days', max_digits=5)),
                ('total_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12)),
                ('status', models.CharField(choices=[('Confirmed', 'Confirmed'), ('Cancelled', 'Cancelled')], default='Confirmed', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.customer')),
                ('space', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='booking.space')),
            ],
            options={
                'ordering': ['-booking_date', '-start_time'],
            },
        ),
        migrations.CreateModel(
            name='BlockedDate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField(blank=True, help_text='If empty, blocks the entire day', null=True)),
                ('end_time', models.TimeField(blank=True, help_text='If empty, blocks the entire day', null=True)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('space', models.ForeignKey(blank=True, help_text='If empty, blocks all spaces', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocked_dates', to='booking.space')),
            ],
        ),
    ]
